import { type NextPage } from "next";
import Head from "next/head";
import NavBar from "components/NavBar";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Emmett Hintz</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen bg-slate-800 px-20">
        <div className="h-auto w-32 pb-16 text-red-400">
          <NavBar />
        </div>

        <div className="grid grid-cols-1 gap-x-7 md:grid-cols-2">
          <div className="flex justify-center bg-cover">
            <Image
              src="/Emmett.jpg"
              className="rounded-full h-auto shadow-xl transition-all duration-1000 hover:scale-105 hover:shadow-2xl"
              alt="Emmett Hintz"
              width={450}
              height={450}
            />
          </div>

          <div className="flex flex-col justify-between h-auto text-white">
            <div>
              <h2 className="hover text-8xl font-bold transition-all duration-500">
                Emmett Hintz
              </h2>
            </div>

            <div>
              <h2 className="text-3xl font-bold">Full-Stack Developer</h2>
            </div>
            <div>
              <p className="text-xl">
                Hello! My name is Emmett and I am a rising junior at Colgate
                University and I am teaching myself full stack development.
              </p>
            </div>
            <div>
              <p className="text-xl">
                This summer, I am focusing on building apps that interest me and
                will help me learn new skills. I have a few projects in the
                works, so stay tuned! This fall I will be interning at Tewke as
                a junior developer!
              </p>
            </div>
          </div>

          {/* under picture */}
          <div className="pt-16">
            <p className="text-emerald-400"></p>
          </div>

          {/* Under name */}
        </div>
      </main>
    </>
  );
};

export default Home;
